### ISSUE TITLE
The space at the bottom appears.

### ISSUE THREAD

**Issue by eastswift** [nrlnishan/ViewPager-Swift#25] opened 2017-07-22 12:41 UTC
The space at the bottom appears. 

I used a tab bar.

There is a small margin between the viewpager's viewcontroller and the tabbar. At the bottom

I want to fit this.

**Comment by nrlnishan** [comment] 2017-07-22 13:33
@eastswift What small margin are you talking about? Can you provide screenshots ?

**Comment by eastswift** [comment] 2017-07-22 15:33
I can provide a screenshot, but I do not know your email address. I've already captured it.

**Comment by nrlnishan** [comment] 2017-07-22 15:57
You can upload screenshot at any image uploading site such as [Imgur](http://imgur.com/) and provide the link here

**Comment by eastswift** [comment] 2017-07-22 18:15
http://imgur.com/iiyaytx

The scroll bar is at the maxium bottom.

**Comment by eastswift** [comment] 2017-07-27 04:30
I think this is not a bug. It seems like I'm using the tab bar.

**Comment by nrlnishan** [comment] 2017-07-27 13:53
@eastswift , Thanks for mentioning that. Since its not a bug, I am closing this issue now

**Closed by nrlnishan** 2017-07-27 13:53 UTC
